[remotes.production]
project_id = "ykaawgnggvwleiyzvilf"

[remotes.staging]
project_id = "cxauavfcyfscjnatxino"

[db.seed]
enabled = true
sql_paths = ['./seed.sql']

[functions.submit-report]
verify_jwt = false

[functions.generate-api-key]
verify_jwt = true

[functions.fonnte-webhook]
verify_jwt = false

[functions.get-webhook-errors]
verify_jwt = false
