project_id = "ykaawgnggvwleiyzvilf"

[functions.submit-report]
verify_jwt = false

[functions.generate-api-key]
verify_jwt = true

[functions.fonnte-webhook]
verify_jwt = false

[functions.get-webhook-errors]
verify_jwt = false
