-- ================================================================
-- Migration: Create License Issued Tokens Table (Vendor Tracking)
-- Date: 2026-02-27
-- Purpose:
--   Track license tokens generated by the vendor/superadmin.
--   This is the vendor-side ledger — NOT used for validation (tokens
--   are validated via Ed25519 cryptographic signature in the Edge Function).
-- ================================================================

CREATE TABLE IF NOT EXISTS public.license_issued_tokens (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  token_id BIGINT NOT NULL UNIQUE,              -- uint32 packed in token payload
  tenant_id UUID REFERENCES public.tenants(id) ON DELETE SET NULL,
  plan_tier TEXT NOT NULL DEFAULT 'starter',   -- starter | pro | enterprise
  max_users INTEGER NOT NULL DEFAULT 10,
  duration_days INTEGER NOT NULL DEFAULT 365,
  features_bitmap INTEGER NOT NULL DEFAULT 1,
  customer_id INTEGER,                         -- customer_id in token payload
  notes TEXT,                                  -- internal notes
  status TEXT NOT NULL DEFAULT 'issued',       -- issued | activated | revoked
  issued_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  activated_at TIMESTAMPTZ,
  revoked_at TIMESTAMPTZ,
  revoked_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- RLS: superadmin only (this is a vendor-side table)
ALTER TABLE public.license_issued_tokens ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE tablename = 'license_issued_tokens'
      AND policyname = 'superadmin_all_issued_tokens'
  ) THEN
    CREATE POLICY "superadmin_all_issued_tokens"
      ON public.license_issued_tokens
      FOR ALL
      USING (has_role(auth.uid(), 'superadmin'));
  END IF;
END $$;

-- Sequence for auto-incrementing token_id (uint32, starts at 1)
CREATE SEQUENCE IF NOT EXISTS public.license_token_id_seq
  START WITH 1
  INCREMENT BY 1
  MINVALUE 1
  MAXVALUE 4294967295
  CYCLE;

-- Updated_at trigger (uses the existing update_updated_at_column function)
CREATE TRIGGER set_license_issued_tokens_updated_at
  BEFORE UPDATE ON public.license_issued_tokens
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
