// =============================================================================
// redeem-license Edge Function
// Validates an Ed25519-signed license token offline (no vendor DB needed),
// then stores the activation in the local tenant database.
//
// Token format: 84-byte binary (20-byte payload + 64-byte Ed25519 signature)
// Encoded as Base32-Crockford, formatted in 8-char groups with hyphens.
// =============================================================================

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.39.3'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
}

// ⚠️ REPLACE THIS with your actual Ed25519 public key hex (64 hex chars = 32 bytes)
// Generated by running: node scripts/generate-license-keypair.js
// The PRIVATE key is stored securely in citizen-admin-hub environment ONLY.
const PUBLIC_KEY_HEX = Deno.env.get('LICENSE_PUBLIC_KEY') || ''

// Base32-Crockford alphabet (no I, L, O, U)
const CROCKFORD_ALPHABET = '0123456789ABCDEFGHJKMNPQRSTVWXYZ'
const CROCKFORD_DECODE_MAP: Record<string, number> = {}
for (let i = 0; i < CROCKFORD_ALPHABET.length; i++) {
  CROCKFORD_DECODE_MAP[CROCKFORD_ALPHABET[i]] = i
}

function base32CrockfordDecode(input: string): Uint8Array {
  const str = input.toUpperCase().replace(/-/g, '').replace(/\s/g, '')
  const bits: number[] = []

  for (const char of str) {
    const val = CROCKFORD_DECODE_MAP[char]
    if (val === undefined) throw new Error(`Invalid Base32 character: ${char}`)
    for (let i = 4; i >= 0; i--) {
      bits.push((val >> i) & 1)
    }
  }

  const bytes = new Uint8Array(Math.floor(bits.length / 8))
  for (let i = 0; i < bytes.length; i++) {
    let byte = 0
    for (let j = 0; j < 8; j++) {
      byte = (byte << 1) | bits[i * 8 + j]
    }
    bytes[i] = byte
  }
  return bytes
}

// Parse the 20-byte payload
interface TokenPayload {
  version: number
  token_id: number
  customer_id: number
  plan_tier: number  // 1=starter, 2=pro, 3=enterprise
  max_users: number
  duration_days: number
  issued_at: number  // Unix timestamp
  features_bitmap: number
}

function parsePayload(bytes: Uint8Array): TokenPayload {
  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength)
  return {
    version:        view.getUint8(0),
    token_id:       view.getUint32(1, false),  // big-endian
    customer_id:    view.getUint16(5, false),
    plan_tier:      view.getUint8(7),
    max_users:      view.getUint16(8, false),
    duration_days:  view.getUint16(10, false),
    issued_at:      view.getUint32(12, false),
    features_bitmap: view.getUint32(16, false),
  }
}

const PLAN_TIER_NAMES: Record<number, string> = {
  1: 'starter',
  2: 'pro',
  3: 'enterprise',
}

// Decode JWT payload without re-verifying (verify_jwt:true at gateway already did that)
function decodeJwtPayload(token: string): Record<string, any> {
  const parts = token.split('.')
  if (parts.length !== 3) throw new Error('Invalid JWT structure')
  const base64 = parts[1].replace(/-/g, '+').replace(/_/g, '/')
  const padded = base64.padEnd(base64.length + (4 - base64.length % 4) % 4, '=')
  return JSON.parse(atob(padded))
}

async function hexToBytes(hex: string): Promise<Uint8Array> {
  const bytes = new Uint8Array(hex.length / 2)
  for (let i = 0; i < bytes.length; i++) {
    bytes[i] = parseInt(hex.substring(i * 2, i * 2 + 2), 16)
  }
  return bytes
}

async function bytesToHex(bytes: Uint8Array): Promise<string> {
  return Array.from(bytes).map(b => b.toString(16).padStart(2, '0')).join('')
}

async function sha256Hex(data: Uint8Array): Promise<string> {
  const hashBuffer = await crypto.subtle.digest('SHA-256', data)
  return bytesToHex(new Uint8Array(hashBuffer))
}

async function verifyEd25519(
  payload: Uint8Array,
  signature: Uint8Array,
  publicKeyHex: string
): Promise<boolean> {
  try {
    const publicKeyBytes = await hexToBytes(publicKeyHex)
    const key = await crypto.subtle.importKey(
      'raw',
      publicKeyBytes,
      { name: 'Ed25519' },
      false,
      ['verify']
    )
    return await crypto.subtle.verify(
      { name: 'Ed25519' },
      key,
      signature,
      payload
    )
  } catch (err) {
    console.error('Ed25519 verify error:', err)
    return false
  }
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  if (req.method !== 'POST') {
    return new Response(
      JSON.stringify({ error: 'Method not allowed' }),
      { status: 405, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  }

  const authHeader = req.headers.get('Authorization')
  if (!authHeader) {
    return new Response(
      JSON.stringify({ error: 'Missing authorization header' }),
      { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  }

  const supabaseUrl = Deno.env.get('SUPABASE_URL')!
  const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!

  // Service client for all DB operations (verify_jwt:true already validated the user)
  const serviceClient = createClient(supabaseUrl, supabaseServiceKey)

  try {
    // 1. Extract user ID from JWT claims (gateway already verified the signature)
    const jwt = authHeader.replace('Bearer ', '')
    let userId: string
    try {
      const claims = decodeJwtPayload(jwt)
      userId = claims.sub
      if (!userId) throw new Error('Missing sub claim')
    } catch (_) {
      return new Response(
        JSON.stringify({ error: 'Unauthorized' }),
        { status: 401, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // 2. Check role (must be owner or admin)
    const { data: roleData } = await serviceClient
      .from('user_roles')
      .select('role')
      .eq('user_id', userId)
      .single()

    if (!roleData || !['owner', 'admin', 'superadmin'].includes(roleData.role)) {
      return new Response(
        JSON.stringify({ error: 'ACCESS_DENIED', message: 'Hanya owner atau admin yang dapat mengaktifkan lisensi.' }),
        { status: 403, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // 3. Get user's tenant ID
    const { data: profileData } = await serviceClient
      .from('profiles')
      .select('tenant_id')
      .eq('id', userId)
      .single()

    if (!profileData?.tenant_id) {
      return new Response(
        JSON.stringify({ error: 'TENANT_NOT_FOUND', message: 'Tenant tidak ditemukan.' }),
        { status: 404, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }
    const tenantId = profileData.tenant_id

    // 4. Parse request body
    const { token_code } = await req.json()
    if (!token_code || typeof token_code !== 'string') {
      return new Response(
        JSON.stringify({ error: 'TOKEN_REQUIRED', message: 'token_code wajib diisi.' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // 5. Decode Base32-Crockford token → 84 bytes
    let tokenBytes: Uint8Array
    try {
      tokenBytes = base32CrockfordDecode(token_code)
    } catch (_) {
      return new Response(
        JSON.stringify({ error: 'TOKEN_FORMAT_INVALID', message: 'Format token tidak valid.' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    if (tokenBytes.length !== 84) {
      return new Response(
        JSON.stringify({ error: 'TOKEN_LENGTH_INVALID', message: 'Panjang token tidak valid (harus 84 bytes).' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // 6. Split payload (20 bytes) and signature (64 bytes)
    const payload = tokenBytes.slice(0, 20)
    const signature = tokenBytes.slice(20, 84)

    // 7. Verify Ed25519 signature
    if (!PUBLIC_KEY_HEX) {
      console.error('LICENSE_PUBLIC_KEY environment variable not set!')
      return new Response(
        JSON.stringify({ error: 'SERVER_CONFIG_ERROR', message: 'Konfigurasi server tidak lengkap.' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    const isValid = await verifyEd25519(payload, signature, PUBLIC_KEY_HEX)
    if (!isValid) {
      return new Response(
        JSON.stringify({ error: 'TOKEN_SIGNATURE_INVALID', message: 'Token tidak valid atau telah dipalsukan.' }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // 8. Parse payload fields
    const parsed = parsePayload(payload)

    if (parsed.version !== 1) {
      return new Response(
        JSON.stringify({ error: 'TOKEN_VERSION_UNSUPPORTED', message: `Versi token ${parsed.version} tidak didukung.` }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // 9. Compute SHA-256 hash of full 84 bytes (anti-reuse key)
    const tokenHash = await sha256Hex(tokenBytes)

    // 10. Check if this token was already redeemed
    const { data: existingActivation } = await serviceClient
      .from('license_activations')
      .select('id, activated_at')
      .eq('token_hash', tokenHash)
      .maybeSingle()

    if (existingActivation) {
      return new Response(
        JSON.stringify({
          error: 'TOKEN_ALREADY_USED',
          message: 'Token ini sudah pernah digunakan.',
        }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // 11. Calculate expiry date
    //     If tenant has an active license that hasn't expired yet, EXTEND from that date.
    //     Otherwise, start from now.
    const { data: currentTenant } = await serviceClient
      .from('tenants')
      .select('license_expires_at, license_status')
      .eq('id', tenantId)
      .single()

    const now = new Date()
    let expiryBase: Date

    if (
      currentTenant?.license_expires_at &&
      currentTenant.license_status === 'active' &&
      new Date(currentTenant.license_expires_at) > now
    ) {
      // Extend from existing expiry date
      expiryBase = new Date(currentTenant.license_expires_at)
    } else {
      // Start fresh from today
      expiryBase = now
    }

    const expiresAt = new Date(expiryBase)
    expiresAt.setDate(expiresAt.getDate() + parsed.duration_days)

    const planName = PLAN_TIER_NAMES[parsed.plan_tier] || 'starter'
    const issuedAtDate = new Date(parsed.issued_at * 1000)

    // 12. Insert activation record
    const { error: insertError } = await serviceClient
      .from('license_activations')
      .insert({
        token_hash: tokenHash,
        token_id: parsed.token_id,
        plan_tier: planName,
        max_users: parsed.max_users,
        duration_days: parsed.duration_days,
        features_bitmap: parsed.features_bitmap,
        customer_id: parsed.customer_id,
        issued_at: issuedAtDate.toISOString(),
        activated_at: now.toISOString(),
        expires_at: expiresAt.toISOString(),
        tenant_id: tenantId,
      })

    if (insertError) {
      console.error('Insert activation error:', insertError)
      return new Response(
        JSON.stringify({ error: 'ACTIVATION_FAILED', message: 'Gagal menyimpan aktivasi lisensi.' }),
        { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    // 13. Update tenant's license state
    const { error: updateError } = await serviceClient
      .from('tenants')
      .update({
        license_status: 'active',
        license_expires_at: expiresAt.toISOString(),
        license_plan: planName,
        license_max_users: parsed.max_users,
        license_features_bitmap: parsed.features_bitmap,
        license_activated_at: now.toISOString(),
        updated_at: now.toISOString(),
      })
      .eq('id', tenantId)

    if (updateError) {
      console.error('Update tenant error:', updateError)
      // Don't fail the request — activation record is already saved
      // The tenant row can be updated via retry
    }

    // 14. Return success
    return new Response(
      JSON.stringify({
        success: true,
        message: 'Lisensi berhasil diaktifkan!',
        license: {
          status: 'active',
          plan: planName,
          max_users: parsed.max_users,
          duration_days: parsed.duration_days,
          features_bitmap: parsed.features_bitmap,
          activated_at: now.toISOString(),
          expires_at: expiresAt.toISOString(),
          days_remaining: parsed.duration_days,
        },
      }),
      {
        status: 200,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    )

  } catch (err) {
    console.error('Unexpected error in redeem-license:', err)
    return new Response(
      JSON.stringify({
        error: 'INTERNAL_ERROR',
        message: err instanceof Error ? err.message : 'Internal server error',
      }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  }
})
